# Conclusions: Rave, Algorithms, and the 'Politics of Musicking'

>“Algorave is made from
‘ sounds wholly or predominantly
characterised by the emission of a succession
of repetitive conditionals’”^[www.algorave.com/about (cf. Criminal Justice and Public Order Act 1994, c.33. Part V – see note 6)]


The discussion carried out so far has let to arise several aspects characterising Algorave as a complex and multi-faceted social phenomenon.
This is reflected, for instance, in the emergence of four distinct dimensions – _practical_, _situational_, _normative_, and _collective_ – within the first phase of conceptualisation resulting from the investigation of the particular meanings associated with the term over the years. Furthermore, considering its social dimension – in this study, closely related to its musicking essence – allowed to frame the phenomenon as a specific form of collective action. In this sense, Algorave has been argued to be constituted by _a network of normed social events, individual actors and communities_, emerging from the pre-existing cluster of musicking interactivity which I referred to as the _‘live coding world’_ (Ch. \@ref(algorave)).
If a ‘music world’ has been said to be based, among other factors, on ‘organisational and/or political ethos’ (Crossley, 2020: 73), it is interesting here to conclude questioning the significance of this aspect for the emergence of a specific region within it – as in the case of Algorave with respect to the broader live coding world.
In order to do that, my suggestion is to begin with a step back, considering the cultural background of the live coding world.
In his already mentioned work, Mori (2020) argues that “[l]ive coders form a rather multifaceted community because they stem from many different [cultural groups]” (Ibidem: 217), suggesting two of them as particularly influencing for this world: the _‘hackers’_ and the _‘makers’_.
Considering the legacy, both in terms of values (Sect. \@ref(hacking-raves)) and practices (Sect. \@ref(making-alternative-spaces-or-the-politics-of-musicking)), of these two cultural groups for Algorave and the live coding world in general, I argue, offers a chance to eventually provide an alternative interpretation of Algorave, letting emerge a final dimension which can be associated with this experience, namely the _political_ one, and its significance at the wider societal level.


## _Hacking raves_

Within the last two decades, algorithms – software, and the ‘digital’^[“More a set of meanings, objects and practices than a technical ordering of information per se, the digital represents characteristic forms of organizing an increasingly interconnected and computerized world expressed in everyday behaviours, discourses and relations” (Prior, 2018: 14).] in general – have become an almost inextricable component of our everyday life.
During this period, it has been possible to witness a shift in our daily routines, rendered increasingly intertwined with the action of these digital entities, and, to a certain extent, influenced by the outcome of their subtle processes. The Covid-19 global pandemic seems to have even accelerated this process, substituting “remote interactions by electronic media for many forms of coordinated work, for schooling and for social gatherings” (Collins, 2020: 478). Of course, musicking practices – both relating to music making and music consumption – are no exception either, having remained no strangers to this change (e.g., Prior, 2018, see also Théberge, 1997).
Despite the central function acquired in Western societies over the years, algorithms are usually treated on the one hand as “incredibly valuable patented trade secrets” (Seyfert and Roberge, 2016: 2), and on the other hand as apparently obscure entities, too complex for our understanding. And yet not for everyone.
According to the ‘Jargon File’ (ver. 4.4.7), a commonly credited source in the field, the term _‘hacker’_ refers to “[a] person who enjoys exploring the details of programmable systems and how to stretch their capabilities”.^[Source: http://www.catb.org/jargon/html/H/hacker.html (last accessed: 12/05/2022). Regarding the history of the early adoption of the term see Levy, 1984. For terminological clarification, note that in this work the term ‘hacker’ is considered distinct from the one of ‘cracker’, namely the one “who breaks security on a system”, a term “[c]oined ca. 1985 by hackers in defense against journalistic misuse of [the term] hacker” (‘Cracker’ in the Jargon File 4.4.7, available at http://www.catb.org/jargon/html/C/cracker.html, last accessed: 12/05/2022).]
Steven Levy (1984) argues to have “found […] a common philosophy” linking the “true hackers of the MIT artificial intelligence lab in the fifties and sixties” to “the young game hackers who made their mark in the personal computer of the eighties” (Levy, 1984: ix-x).
In his earlier attempt of abstracting the main values associated with this cultural group,^[Another remarkable example is provided by Ted Nelson, in his pioneering ‘Computer Lib/Dream Machines’ (1987 [1974]).] he reported the following six propositions,^[The reported excerpts are retrieved from Levi (1984), pages 28-38. The letters are not present in the original text; these have been associated to the principles to provide reference in the discussion which follows.] to which he referred to as “the tenets of hackerism” (Ibidem, 28):

[A] _Access to computers – and anything that might teach you something about the way the world works – should be unlimited and total. Always yield to the Hands-On Imperative!_
[B] _All information should be free._
[C] _Mistrust Authority – Promote Decentralization._
[D] _Hackers should be judged by their hacking, not bogus criteria such as degrees, age, race, or position._
[E] _You can create art and beauty on a computer._
[F] _Computers can change your life for the better._

Years later, Pekka Himanen (2001), in his _“The Hacker Ethic and the Spirit of the Information Age”_, identifies seven additional ‘values’ – to some extent relating with the principles above mentioned – associated with his conceptualisation of ‘hacker ethic’, specifically relating to the three dimensions of work, money, and _‘nethic’_.^[Namely network ethic, as distinguished by ‘netiquette’, which in turn concerns ‘behavioral principles’ for communication on Internet – e.g., ‘avoid flames’ (see Himanen, 2001: 85-138).]
Those are _passion_, “some intrinsically interesting pursuit that energizes the hacker and contains joy in its realization”; _freedom_, relating to intend their work activities “in terms of a dynamic flow between creative work and life’s other passions”; _social worth_ and _openness_, as “hackers want to realize their passion together with others, […] [allowing] the results of their creativity to be used, developed, and tested by anyone so that everyone can learn from one another”; _activity_, “[involving] complete freedom of expression in action, privacy to protect the creation of an individual lifestyle, and a rejection of passive receptiveness in favor of active pursuit of ones’ passion”; _caring_, intended as to “concern for others as an end in itself […] getting everybody to participate in the network and to benefit from it”; and, eventually, _creativity_, “that is the imaginative use of one’s own abilities, the surprising continuous surpassing of oneself, and the giving to the world of a genuinely valuable new contribution” (Ibidem, 139-141).
Considering the aspects emerging from the literature above referenced, it is interesting to observe how more than few similarities with earlier discussed aspects related to live coding and Algorave are traceable.
In general, live coders are argued to “release all their software under open-source or free software licenses”, despite they “seem not particularly interested in the freedom issue that may derive from the use of non-free software” (Mori, 2020: 229-30).^[As also witnessed, according to Mori (2020), by the widespread use among live coding practictioners of Apple devices and related software.]
In spite of any potential divergences with the “more radical and idealistic branch of hacker community” (Ibidem, 221),^[Represented by the Free Software Movement and in the figure of Richard M. Stallman, its creator (see Stallman et al., 2002).] _openness_ represents an important value within the live coding world. The creative work of the live coders in programming software for the performances is substantiated by sharing it not only with the rest of the community, but allowing anyone interested to use it – and improve or adapt it to their own needs.
Live coders, I would argue, make a step even further in this direction, by ‘opening’ the creative processes underlying their performances. By displaying the operating processes through the projection of their screen, they simultaneously show how the music – or visual, or whatever is the practice outcome of the algorithmic part in the performance – is created. Indeed, as clearly stated in the TOPLAP Manifesto, contrasting “Obscurantism”, the “[c]ode should be seen as well as heard, underlying algorithms viewed as well as their visual outcome”.^[https://toplap.org/wiki/ManifestoDraft (last accessed: 13/05/2022).] As already mentioned (cf. Ch. \@ref(algorave)), this represents an element also specifically characterising performance at Algorave events.
Moreover, “[f]or live coders computers remain a crucial device for work, but […] contemporarily an artistic tool” (Mori, 2020: 228), actualizing the idea according to which ‘art and beauty’ can be created with these machines (see point E).
Further parallels between hacker ethic and Algorave can be made re-introducing its _normative dimension_, hence referring to the _‘organizational conventions’_ and _‘behavioural norms’_ distinguishing Algorave events. In this sense, it is also deemed interesting to consider in view of this parallelism the other culture to which Algorave specifically relates, namely Rave Culture.
A first among these aspects refers to diversity – both in line-ups and audiences. This underlies a particular attention for inclusiveness, which may be conceptually linked, on one side, to the value of _caring_, and on the other, with the due precautions, to the point D. Indeed, the attention for inclusiveness can be intended as a form of ‘concern for the others’, regarded ‘as an end’ of the action ‘in itself’, to be reached by ‘getting everybody to participate in the network’. This seems to be also confirmed in accounts of live coding in general, as “many live coders are interested in building a community in which everyone may participate and feel at home as if they had always been friends with the members of the community” (Mori, 2020: 232). Moreover, to some extent, embracing diversity is to refuse _‘bogus criteria’_ such as _‘degrees, age, race, or position’_. An important distinction has here to be made, though. No judging – in the sense used by Levi (1984: 31) – is involved at all in Algorave. While “to create new programs to admire” and “to talk about that new feature in the system” may still have a value, in Algorave no one  has neither to “prove” him or herself “at the console of a computer” (Ibidem), nor to be judged. Quite the opposite indeed, considering the acceptance and encouragement reserved for beginners, as I personally experienced in my brief ‘career’ as live coder.
From a sociological perspective, one crucial element within the aspect of diversity is gender, along with the _roles_ to it associated.
The analysis (cf. Sect. \@ref(the-algorave-performers-musicking-network) and \@ref(collective-tours-local-adoption-and-the-long-travel-of-the-algorave-evangelists)) revealed some of the women performers present in the sample as holding central positions, as well as playing a crucial role – namely, the one of _‘travelling evangelist’_ – in the development of the phenomenon.
Overall, it has been noted how the ‘carrier group’ – namely the core of the network composed by the performers – presents a fairly balanced distribution of males and females (6 to 4), and despite all the due caution in generalisation (see Sect. \@ref(collective-tours-local-adoption-and-the-long-travel-of-the-algorave-evangelists); see also Armitage and Thornham, 2021) this still represents an interesting result. Particularly due to the fact that women are usually argued to be prevented from holding such positions and roles (e.g., Cohen, 1991), especially in the field of electronic music and within club culture – if not their “experiences [to be] ‘written out’ of youth-cultural histories” (Pini, 1977: 153; see also McRobbie, 1984).
Rave in this sense represents an interesting case in point, as despite it “can be seen as indicating an important shift in sexual relations – a general ‘feminisation’ of youth’”, women are argued to be “relatively [absent] at the levels of […] production and organisation” (Pini, 1977: 168).
This gender balance in holding important roles acquires even further meaningfulness, considering the already mentioned gender-related cultural bias, by which women are seen as alien to computer science field (Armitage, 2018) and, more generally, as properly capable of make use of these machines.^[One resonant example in this sense is provided by the absence of any reference to gender in the categories mentioned in point D of Levi (1984).]
Another important aspect within the ‘organizational conventions’ is the one regarding the relationship with institutions. As expressed in the General Guidelines (see Appendix \@ref(appendix-a---algorave-general-guidelines-and-code-of-conduct)), the organisers are invited to ‘be wary’ of these, evaluating carefully any ‘sponsorship or institutional alignment’. A clear connection with one of the points reported by Levi (1984) – [C] _‘Mistrust Authority’_ – is emerging, particularly if considering the statement in the Guidelines which reads _‘Algorave is free culture’_.
Nevertheless, within the first five years, the share of Algorave events which have benefited from any kind of institutional support for their organisation represents around the 40% of the total. While rave, after an early phase as “grassroots organized, anti-establishment and unlicensed all-night dance parties” (Anderson and Kavanaugh, 2007: 500), has undergone a process of institutionalisation,^[Here with the term I refer to the transition toward ‘legality’ experienced in the organisation of raves (Gilbert and Pearson, 1999, in particular ch. 7, 158-186). ] Algorave presents itself from the outset as more open to benefit from the support provided by institutions. As earlier pointed out, though,^[See note 68 (Sect. 2.3).] and similarly to the previous aspect, further research more specifically addressing this sole aspect are deemed needed.
Thus, considering the results of this brief comparison, if on one side the legacies of both hacker and rave culture are clearly emerging when discussing Algorave, on the other it can be said that this latter ‘hacked’ both its predecessors. Indeed, carrying out, not only a discourse inherent to, but an enactment of the value of equality, Algorave openly challenged sedimented cultural bias and re-discuss the relationship between decentralized communities and institutions.

Eventually, if “the collective nature of musicking at raves [poses] a challenge to the individualism of contemporary societies” (Crossley, 2020: 189), and “hackers” have been argued of “[wanting] to realize their passion together with others” (Himanen, 2001: 140) with the final intent of “giving to the world of a genuinely valuable new contribution” (Ibidem, 141), thus the ultimate question to be posed is what is the aftermath, at the societal level, of Algorave experience’s collective dimension and its formation process?


## _Making alternative spaces, or the 'politics of musicking'_

In the last chapter of his book ‘Connecting Sounds’, Nick Crossley (2020: 170-191) expressly addresses the issue of “music’s political dimension”.
Of particular interest for the present discussion, is the final point discussed by the author where, moving beyond the “formal, institutionalised sense” of politics, he proposes to account for “a different sense of politics, […] more resonant with accounts of the so-called ‘new social movements’” (Ibidem, 188). In doing so, Crossley considers “particular music worlds” – among them, rave is mentioned as a ‘prominent example’ – in which “issues which fall outside of the parameters of mainstream political discourse” are argued to be addressed (Crossley, 2020: 188).
Linking these formations to ‘new social movements’ theories (see Melucci, 1989),

>“participants in [these] particular music worlds, though disgruntled with their wider society, have little faith in either institutionalised politics or the claims of self-styled revolutionary sects to bring about meaningful change; they therefore seek to create alternative ‘spaces’ in which they can, albeit only temporarily, escape from the conditions they reject in the ‘outside world’ and act in accordance with their own alternatives within the context of a wider society whose values and structure they criticise” (Crossley, 2020: 189).


Sarah Thornton (1996), in this sense, suggests the “carving out of cultural spaces” by youth – e.g., the ‘underground’ – to make a _distinction_ “from parent cultures”, creating a “space of youth culture which do not follow the parameters of those stratifying wider society, but which none the less serve a stratifying purpose” (Gilbert and Pearson, 1999: 159).
Another example is provided by the understanding of rave as ‘Temporary Autonomous Zones’ (TAZ), a “fully ‘spatialized’ political tactic, […] concerned with carving out ‘autonomous space’” (Ibidem: 163).^[In this sense, Gilbert and Pearson (1999: 163) point out “that it always ends up leaving the big power structures in place”. The problem according to Gilbert and Pearson (1999) is that: "[t]here might be a severe danger of dance culture simply serving as a social safety-valve, a distraction and consolation for a generation for whom prospects for secure jobs, rising standards of living and opportunities for democratic control over their own lives all look bleak" (Ibidem, 1999: 163). For a discussion on musicking as political 'safety-valve' (Halnon, 2005, cit. in Crossley, 2020), for critical account on this perspective see Crossley (2020: 173-4).]
This space-creation also reflects in music, as it represents – similarly to art, in general – “a space where human freedom and potential can be nurtured”, in which “challenges to convention” – not only, I would argue – “within art music [excite the] reflective and critical capacities” of audiences (Crossley, 2020: 170-1). In this sense, music is exhibiting its ‘critical potential’^[In the sense of Adorno, when referring to the ‘more avant-garde musical forms’ (in Crossley, 2020: 170; for a critique of the relatively debated Adorno’s understanding of popular music, see also pp. 174-177).] not so much for its content per se, as, for example, a song lyric referring to political issues might be, but in relation to “the _form_ of musicking works” (Crossley, 2020: 170; see also Jarvis, 2007).
In this light, rather than by what can be said to be characterising it – e.g., a certain aesthetic in music or visual – Algorave can then be regarded by the specific form taken by its organisation, which is to say, from the perspective adopted within the present study, how a collective around this specific understanding of live coding practice has been created. In other words, how a group of commonly-oriented individuals has been able to ‘make’ a global ‘alternative space’ connecting a wide variety of particular socio-cultural contexts, which, besides fundamental particularistic differences deriving from local adoption and adaptation of this understanding, can be regarded as been emerging as a ‘whole’, or, in Melucci’s terms (1996), the process of _Algorave collective identity_.
During the discussion, I argued that Algorave community resembles another kind of collective formation, namely ‘protest communities’ (Diani, 2009). Indeed, despite none of the two is constitutive of nor is based on associations, in both of these cases a “distinct sense of commonality and specific bonds between people” are originated by their _repeated sharing of the same experiences_, accessed through the “recurrent participation” at specific events (Diani, 2009: 66). In this sense, I specifically addressed the process of collective formation by framing it as constructing ‘event after event’.
In the analysis, this perspective has been adopted from two different angles; respectively, by considering the structure of events – what I referred to as the _‘Algorave events system’_ – linked one another on the basis of the presence of common performing actors, and, conversely, by looking at the network of these last, the _‘Algorave Performer Network’_, resulting from their shared participation to the same events. This twofold overview allowed to bring forth two crucial aspects regarding how the actors involved in the Algorave action _collectively_ experience it.^[Somehow reinforcing, from a methodological perspective, the idea according to which the adoption of single-mode projection-based analytical strategy not necessarily implies a loss of data (Everett and Borgatti, 2013), actually representing a useful technique to simplify and letting the attention to be focused on specific aspects under investigation. Moreover, again from this perspective, network-centred approach results more than adequate both for the theoretical study and the analyitical of the relational dynamics and mechanisms underlying the construction of a collective formation.]
On the one hand, specifically investigating the meaningfulness of events sequences, allowed to shedding light on a particular dynamic characterising the Algorave collective organisation: _‘collective touring’_.
In previous literature the role of ‘tour’ has been described as relevant to forge and reinforce the relationships which favours the constitution of ‘translocal’ communities (Verbuč, 2022). If this aspect found evidence also in the case of Algorave, the one associated to this last is distinguishable from other better-known forms of touring – e.g., those of the live music industry – for the creation of temporary collectives, situationally sharing a longer-than-one-show experience together. As argued, this would favour the establishment of durable ties among participants, eventually contributing to the formation of a wider collectivity.
On the other hand, by examining the network of performers over the first five years of the phenomenon, it has been possible to identify an emerging mechanism within the process of collective formation.
Once assessed the presence of a carrier group, composed by those who performs at more events together, it was interesting to note that these key figures are not only the ones translocally bridging different communities, but that at least one of these was participating to the first event organised in a country where no sign of Algorave was previously traceable.
Recalling Gerlach’s (1971) conceptualisation of movement structures, I referred to them as holding a role of “criss-crossing” the live coding world and the musical universe, “as living links in the reticulate network” (Ibidem, 823), from which the definition as the _‘travelling Algorave evangelists’_. This role has been argued to be dual, in the sense that it comprises both the activity of bonding the participants and the one of introducing Algorave in new socio-cultural contexts.

While I hitherto referred to this introduction as exclusively involving a specific ‘understanding of live coding practice’, in consideration of the elements discussed in this chapter so far, I now suggest making a step further in the interpretation.
Similarly to ‘protest communities’ (see Diani, 2009: 66), it would be also possible to affirm that Algorave participants in their action promote at the same time a specific _‘world-view’_, based on the values previously discussed and contextually underlying a challenging, and in this sense _political_ dimension.
According to Crossley (2020), “[a]lternative music worlds might challenge the norms and assumptions of ‘wider society’, but they also often challenge conventional musicking practices” (Ibidem, 190).

With regards to the firsts, reporting the suggestion by Ruiz-del Olmo and colleagues (2019), Algorave can be intended as

>“a space on the fringes of [a] control system where algorithms are used for purposes outside the interests of the system itself. It is a space of creation where the main material is the algorithm itself, with which the state of well-being destined for an end user is deconstructed. Here, the user is able to construct his creative process through the programming code, maintaining a distance from the control system” 
>(Ruiz-del Olmo et al., 2019: 427). 

Algorave here represents a space at the periphery of the ‘control system’ – expression of the previously mentioned ‘wider society’, _alternative_ to it in the use of algorithms, and related purposes, diverging from the ‘interests of the system itself’. ‘Users’ re-acquire agency with respect to algorithms ‘through [creative] programming’, while ‘maintaining a distance from the control system’, where they are relegated to the role of ‘end user’.^[Cf. Appendix \@ref(appendix-b---set-the-algorithm-in-motion-live-scripting-and-the-human-algorithm-interaction-in-social-situations). Note in particular the differences between model presented in Figure B1 and the one proposed in Fig. B2, and the related discussion.]
This use of algorithms, “rather than signalling technological progress”, characterises Algorave to “[signal] an unravelling of technology” (McLean, 2019: 176).^[“[S]tripping back years of interface development to re-expose computers as language machines” (McLean, 2019: 176).] As well as, specifically considering its ‘openness’ feature – linking with the related value previously associated to the phenomenon, it “ has come to signify a very different _social attitude_ in the context of the intellectual property rules of the dominant corporate socio-economic model” (Ruiz-del Olmo, 2019: 436, emphasis added), which found expression in the Algorave experience.
Hence, Algorave political dimension in relation with ‘wider society’ emerges as the challenge by the individuals forming this collective to the ‘norms and assumptions’ concerning both technology in general and  the ‘dominant corporate socio-economic model’ which governs it, for instance through ‘intellectual property rules’.
On the other hand, challenges to “conventional musicking practices” (Crossley, 2020: 190), the _‘politics of musicking itself’_ as Crossley calls it, are also characterising the emerging political dimension of Algorave.
In this sense, in the previous section, Algorave has been underlined as attempting to challenge, or _‘hacking’_, the cultural bias inherited by cultural groups from which it originates, and their consequences – as in the case of gender under-representation in relevant roles within the organisation and active participation to musicking.
Further evidence emerged, particularly with regards to Algorave events and their organisation, pointing at challenges within these levels to dominant socio-economic – which is to say music industry-based – way of conceiving musicking.
Firstly, a challenge is posed at the level of performance. This finds evidence, for instance, in the refusal of hierarchisation among the performers, in clear opposition to the archetype of what is considered to be an ‘unequal’ performance, centred more on the performer’s status – e.g., the ‘headliner’ – than on his or her music. This marks an analogy with rave, which “spirit of semi-anonymous people playing to unified crowds” is expressly mentioned in the General Guidelines for Algorave event organisation (See Appendix \@ref(appendix-a---algorave-general-guidelines-and-code-of-conduct)).
Another important aspect in this sense is the deconstruction of the idea of musical performance as faultless, by the situational acceptance of error^[Derived from the ‘trial and error’ approach, proper of programming practice.] as part of the performance. This relates to the previous aspect, insofar rather than being intended as a top-down imposition of a virtuoso – or a famed band, Algorave performance is intended as a grassroot co-creation of the situation.
Secondly, challenging elements emerges also at the organisational level. It is worth to remind, in this sense, that Algorave brand is not trademarked, and for this reason anyone can organise an event under this name. While favouring the local adoption and evolution of the phenomenon via adaptation, this represents an important expression of the value of ‘free culture’, as opposed to a business-centred view of musicking.
These are only few examples reported to introduce the challenges at the foundations of the political dimension of Algorave, tracing a possible path for exploration to be followed in further research, not only in relation to this specific phenomenon, but also intended to delve into the relational processes that are at the basis of music worlds’ formation, and cultural movements in general.