# (APPENDIX) Appendix {-} 

# _Algorave General Guidelines and Code of Conduct_


_A.1) General guidelines_

Retrieved from https://github.com/Algorave/guidelines/blob/master/README_en.md

**FIRST AND FOREMOST:** By all means, please go ahead and host/promote an Algorave! And have fun. Algorave is not a protected brand or franchise, you are free to do what you like with it. However it is a community, and these are some community-sourced guidelines for taking part.
You can’t go wrong with full range speakers and high contrast ratio projector in a small, dark room, preferably with fog/haze. If you want to do a concert with rows of seats that’s fine but best not call it an Algorave.

**Exposing algorithmic processes** - Most performances/acts should involve code-based and algorithmic generation of music and visuals, in a way that makes the code or algorithmic process visible. It doesn’t have to be live coded, though, and some aren’t comfortable projecting their screens. Beyond that, feel totally free to mix things up with other artforms/approaches in the interests of fun and diversity.

**Be wary of institutions** - Algorave is free culture so be careful with any sponsorship or institutional alignment. It’s totally fine for promoters to perform as residents at Algoraves they’re organising, but don’t go too far with self-promotion. Use Algorave to lift each other up.

**Collapsing hierarchies** - ‘Headliners’ are generally frowned upon. Algoraves are not always ‘raves’ as such, but it’s good to be inspired by some of the spirit of semi-anonymous people playing to unified crowds.

**Respect for other communities** - Algorave is not ‘the future of dance music’, we’re just trying things out as part of a much longer history.

**Diversity in lineups and audiences** - Try to have a diverse lineup, thinking about e.g. gender, ethnicity, class, age, belief/non-belief, and education. A diverse lineup creates a diverse audience which leads to a diverse community, and is beneficial to all. Additionally it is also nice to see a range of different technologies and approaches to keep things moving.

It’s best to focus on diversity right from the start. Once people get the impression of e.g. a boys’ club it’s hard to shake that off.. Plus we’re fighting against heavy biases in both club and tech culture… Look to create a new space from day one.
Algoraves should be safe spaces, consider having a code of conduct to promote accessibility, here’s an example: https://github.com/Algorave/algoraveconduct (See Sect. A2).

**Building local and online communities** - If people are already active in your area, get in contact and get involved. If possible, come along to an Algorave while thinking about organising one yourself. They’re pretty fun.

Online there is an active community of performers and event organizers who are happy to help; they can also provide resources for using the visual identity for promotional materials. Good places are:
-	The #algorave channel on the Live Coding chat: https://chat.toplap.org/channel/algorave
-	For slower discussion, the TOPLAP forum https://forum.toplap.org/
- The algorave forum on Lurk: https://we.lurk.org/postorius/lists/algorave.we.lurk.org/
- Alternatively you can use the contact page on the algorave website: https://algorave.com/contact/


_A.2) Code of Conduct_

Retrieved from https://github.com/Algorave/algoraveconduct/blob/master/conduct_en.md


Where specified, all participants at Algorave events, including attendees, performers, organisers and volunteers, are required to agree with the following code of conduct. Please support it and help ensure a safe environment for everybody.

**What Is This?**
To meet our aim to make inclusive, safe events, we have outlined expectations of participants. This code applies to Algorave, any related social events and online communities around it. For more information on codes of conduct and why they are necessary, see http://www.ashedryden.com/blog/codes-of-conduct-101-faq

**Inclusion**
Please remember that at an Algorave you will have a group with mixed genders, beliefs, technologies, backgrounds, sexualities and so on.
In all communication - whether that be when promoting the event, addressing performers or your audience, try to use inclusive language, e.g. remember that ‘guys’ is not a gender-neutral term in many parts of the world, try not to address a mixed group with that. 