--- 
title: "Feedback Loops and Repetitive Conditionals: Exploring the Algorave Musicking Network Organisation"
author: "Pietro Casari"
site: bookdown::bookdown_site
description: "This is an online public version of my M.A. thesis in 'Sociology
and Social Research' at the University of Trento (Italy), discussed on 31/05/2022.
This publication is shared under a creative commons licence - [CC BY-NC-SA 4.0 - Attribution-NonCommercial-ShareAlike 4.0 International](https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode)."
---









# Preface {-}


This is an online public version of my M.A. thesis in 'Sociology
and Social Research' at the University of Trento (Italy), discussed on 31/05/2022.



This online version is licensed under the [Creative Common Attribution-NonCommercial-ShareAlike 4.0 International](https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode).









# Acknowledgements {-}




Although in the following pages the old adage that a book – or in this case, a dissertation – is to be understood as a ‘collective action’ will be called into question, I would nevertheless like to thank, in first place, all the workers who, more often than not unconsciously, have with their work made it possible to realise this thesis. In particular, for ensuring me a safe experience by strictly applying the measures for the containment of Covid-19, as well as for bending those rules related to exclusive access to the Genoa university library system, my first thanks go respectively to the workers of the Biblioteca Civica Berio and the Biblioteca della Scuola di Scienze Sociali of the University of Genoa. Remaining on the university front, my thanks also go to Professors Elena Pavan and Silvia Sacchetti for accepting the role of co-supervisors for this thesis as well as for their important help in the first phase of developing the issues discussed here. My heartfelt thanks also go to Professor Mario Diani, who has – patiently – assisted me along this path in the role of supervisor. First and foremost, for being able to make me comprehend the potential of the methodology I adopt in this study, while transmitting me his passion, in just the first ten minutes of the introductory lecture of his course. A huge thanks goes also to the Live Coding community in London, for welcoming me into their world, allowing me to better understand it, and gifting me with an unforgettable night on Algorave's 10th birthday. And to the TOPLAP Italia community as well, for their support during my first performance at an Algorave.
Thanks also to the people I have met in Trento over the years – although often, unfortunately, too late – and, in particular, to Filippo and Davide. For the always honest confrontation and precious suggestions, for their last-minute hospitality and laughter. The next round is on me. A special thanks goes to my family. To my parents, for supporting my choice to complete the first five years of my academic career, and for always supporting me and hearing my voice in the choices I have made in my life journey. To my brother, for stimulating my curiosity and critical sense, ever since I was a child. Lastly, I would particularly like to thank Paola, my partner in life and in this journey, which we started together almost three years ago, and which we will conclude in the next few days, together. Without her, I would never have arrived here. And this, which sounds like a cliché, has never meant as much to me as it does in this context. For handing me the right books, for the strength transmitted to me despite the difficult time, for our life _together_, from tomorrow on.